---
title: "Guppy colour learning - experiment 2 analysis"
author: "M. Wyatt Toure"
date: "28/05/2021"
output: html_document
---

```{r library-prep, include=FALSE}
# Loading required packages
library(lme4)
library(tidyr)
library(lmerTest)
library(ggplot2)
library(ggpubr)
library(DHARMa)
library(dplyr)
library(effects)
library(broom)
library(broom.mixed)
library(knitr)
library(emmeans)
library(report)
library(cowplot)
library(tidyext)
library(glmmTMB)
library(MASS)
source("R/format-p-value.R")
source("R/rename-lme4-model.R")
source("R/geom-flat-violin.R")
source("R/read-ethovision-data.R")
```

```{r data-prep, include=FALSE}
# Reading in Data
full_data <- read_and_format_ethovision_data("data/experiment-2-raw-data/")

## Assigning treatments
full_data <- full_data %>%
  mutate(
    rewarding.object.colour =
      case_when(
        id == "1a" ~ "blue",
        id == "1b" ~ "green",
        id == "2a" ~ "blue",
        id == "2b" ~ "blue",
        id == "3a" ~ "blue",
        id == "3b" ~ "green",
        id == "4a" ~ "green",
        id == "4b" ~ "green",
        id == "5a" ~ "green",
        id == "5b" ~ "blue",
        id == "6a" ~ "green",
        id == "6b" ~ "green",
        id == "7a" ~ "blue",
        id == "7b" ~ "blue",
        id == "8a" ~ "green",
        id == "8b" ~ "blue"
      )
  )

# Formatting data

## Factors
Factors <- c("ate", "id", "trial", "object.side", "rewarding.object.colour")
full_data[Factors] <- lapply(full_data[Factors], as.factor)

## Numeric
Numerics <- c(
  "left.object.visits", "time.with.left.object",
  "left.object.latency", "right.object.visits",
  "time.with.right.object", "right.object.latency",
  "periphery.visits", "time.in.periphery",
  "latency.to.periphery", "center.visits",
  "time.in.center", "latency.to.center",
  "distance.moved", "mean.velocity"
)
full_data[Numerics] <- lapply(full_data[Numerics], as.numeric)

# Creating new variables

## Inverting object side
full_data <- full_data %>%
  mutate(
    reward.object.side =
      as.factor(
        case_when(
          object.side == "left" ~ "right",
          object.side == "right" ~ "left"
        )
      )
  )

## Time with trained object
full_data <- full_data %>%
  mutate(
    time.with.trained.object =
      case_when(
        reward.object.side == "left" ~ (time.with.left.object - time.with.right.object),
        reward.object.side == "right" ~ (time.with.right.object - time.with.left.object)
      )
  )

## Time with untrained object
full_data <- full_data %>%
  mutate(
    time.with.untrained.object =
      case_when(
        reward.object.side == "left" ~ (time.with.right.object - time.with.left.object),
        reward.object.side == "right" ~ (time.with.left.object - time.with.right.object)
      )
  )

## Green object preference
full_data <- full_data %>%
  mutate(
    green.object.preference =
      case_when(
        rewarding.object.colour == "green" ~ (time.with.trained.object - time.with.untrained.object),
        rewarding.object.colour == "blue" ~ (time.with.untrained.object - time.with.trained.object)
      )
  )

## Rewarding object preference
full_data <- full_data %>%
  group_by(id) %>%
  mutate(rewarding.object.preference = time.with.trained.object - time.with.untrained.object)

## Trial type
full_data <- full_data %>%
  mutate(
    trial.type =
      as.factor(
        case_when(
          trial == 0 | trial == 21 ~ "test",
          trial > 0 & trial < 21 ~ "training"
        )
      )
  )

# Restrict data to training data
training_data <- full_data %>%
  filter(trial.type == "training")

# Restrict data to only the baseline and re-test data
test_data <- full_data %>%
  filter(trial.type == "test")

# Restrict data to only the baseline data
baseline_data <- full_data %>%
  filter(trial == 0)

# Change trial to factor
test_data$trial <- as.factor(test_data$trial)
baseline_data$trial <- as.factor(baseline_data$trial)
```

```{r model-1, echo=TRUE}
baseline_data_model <-
  lm(green.object.preference ~ 1,
    data = baseline_data
  )
```

```{r, echo=FALSE, message=FALSE}
simulationOutput <- simulateResiduals(fittedModel = baseline_data_model)
plot(simulationOutput)

# Saving plot to figs directory
# ggsave(
#   filename = "exp-2-model-1-residual-plot.png",
#   plot = (plot(simulationOutput)),
#   path = "figs/exp-2/residual-plots/",
#   device = "png",
#   dpi = 300
# )
```

##### Result

```{r tidying-model-1, echo=FALSE, message=FALSE}
# Setting table row names
baseline_table_row_name_vec <- c("Intercept")

# Converting data frame to tibble
tidy_baseline_model <- broom.mixed::tidy(baseline_data_model)

# Changing tibble header names
tidy_baseline_model <- rename_tidy_lme4_cols(tidy_baseline_model)

# Changing tibble row names
tidy_baseline_model[1:1, 1] <- baseline_table_row_name_vec
```

```{r,  results=TRUE, echo=FALSE}
knitr::kable(tidy_baseline_model %>%
  mutate_if(is.numeric, round, digits = 3))
```


```{r baseline-pref-plot, echo=FALSE, message=FALSE, fig.cap="Preference for the green object relative to the blue object across all guppies at baseline. Negative values represent more time spent with the blue object, positive values indicate more time spent with the green object. Data are means +/- 95% CI", fig.id="baseline-pref-plot",  warning=FALSE, message=FALSE}
###### Baseline green object preference plot ######
baseline_data_x_axis_label <- "Initial Test"
ggplot(
  baseline_data,
  aes(
    x = trial,
    y = green.object.preference
  )
) +
  theme_classic() +
  ylab("Green object preference (sec)") +
  xlab("") +
  theme(
    legend.position = "none",
    axis.text = element_text(size = 14),
    axis.title = element_text(size = 14, face = "bold"),
    plot.title = element_text(size = 16, hjust = 0.5)
  ) +
  geom_hline(yintercept = 0, linetype = "dashed", alpha = 0.5) +
  geom_jitter(width = 0.04, alpha = 0.3) +
  stat_summary(
    geom = "point",
    fun = "mean",
    size = 4.5,
    shape = 15
  ) +
  stat_summary(
    geom = "errorbar",
    fun.data = "mean_ci", position = position_dodge(width = 0), width = 0.1
  ) +
  scale_x_discrete(labels = baseline_data_x_axis_label)

# ggsave(
#   filename = "exp-2-model-1-baseline-data-plot.png",
#   path = "figs/exp-2",
#   device = "png",
#   dpi = 300
# )
```

